package net.thenamedev.legendapi.utils;

import java.util.Random;

/**
 * dear god i rektgret nothing (no really I regret nothing - especially of that (horrible) pun)
 *
 * Created on 4/23/2015
 *
 * @author ThePixelDev
 */
public class RektUtils {

    public static String getRandomRekt() {
        Random r = new Random();
        if(PluginUtils.random(2, 1))
            return "☐ Not rekt\n" + rekt[r.nextInt(rekt.length)];
        else
            return "☐ Not rekt\n" + rektgretNothingRekts[r.nextInt(rektgretNothingRekts.length)];
    }

    public static final String[] rekt = {
            "☑ Rekt",
            "☑ Really Rekt",
            "☑ Tyrannosaurus Rekt",
            "☑ Grapes of Rekt",
            "☑ Ship Rekt",
            "☑ Rekt markes the spot",
            "☑ Caught rekt handed",
            "☑ The Rekt Side Story",
            "☑ Singin' In The Rekt",
            "☑ Painting The Roses Rekt",
            "☑ Rekt Van Winkle",
            "☑ Parks and Rekt",
            "☑ Lord of the Rekts: The Reking of the King",
            "☑ Star Trekt",
            "☑ The Rekt Prince of Bel-Air",
            "☑ A Game of Rekt",
            "☑ Rektflix",
            "☑ Rekt it like it's hot",
            "☑ RektBox 360",
            "☑ The Rekt-men",
            "☑ School Of Rekt",
            "☑ I am Fire, I am Rekt",
            "☑ Rekt and Roll",
            "☑ Professor Rekt",
            "☑ Catcher in the Rekt",
            "☑ Rekt-22",
            "☑ Harry Potter: The Half-Rekt Prince",
            "☑ Great Rektspectations",
            "☑ Paper Scissors Rekt",
            "☑ RektCraft",
            "☑ Grand Rekt Auto V",
            "☑ Call of Rekt: Modern Reking 2",
            "☑ Legend Of Zelda: Ocarina of Rekt",
            "☑ Rekt It Ralph",
            "☑ Left 4 Rekt",
            "☑ Pokemon: Fire Rekt",
            "☑ The Shawshank Rektemption",
            "☑ The Rektfather",
            "☑ The Rekt Knight",
            "☑ Fiddler on the Rekt",
            "☑ The Rekt Files",
            "☑ The Good, the Bad, and The Rekt",
            "☑ Forrekt Gump",
            "☑ The Silence of the Rekts",
            "☑ The Green Rekt",
            "☑ Gladirekt",
            "☑ Spirekted Away",
            "☑ Terminator 2: Rektment Day",
            "☑ The Rekt Knight Rises",
            "☑ The Rekt King",
            "☑ REKT-E",
            "☑ Citizen Rekt",
            "☑ Requiem for a Rekt",
            "☑ Star Wars: Episode VI - Return of the Rekt",
            "☑ Braverekt",
            "☑ Batrekt Begins",
            "☑ 2001: A Rekt Odyssey",
            "☑ The Wolf of Rekt Street",
            "☑ Rekt's Labyrinth",
            "☑ 12 Years a Rekt",
            "☑ Gravirekt",
            "☑ Finding Rekt",
            "☑ The Arekters",
            "☑ There Will Be Rekt",
            "☑ Christopher Rektellston",
            "☑ Hachi: A Rekt Tale",
            "☑ The Rekt Ultimatum",
            "☑ Shrekt",
            "☑ Rektal Exam",
            "☑ Rektium for a Dream"
    };

    /**
     * Eh? Get it? REKTgret nothing?<br><br>
     *
     * <em>okay yeah i'll show myself the way out</em>
     */
    public static final String[] rektgretNothingRekts = {
            "☑ anoREKTic",
            "☑ anoREKTics",
            "☑ bidiREKTional",
            "☑ bidiREKTionally",
            "☑ clitoREKTomies",
            "☑ clitoREKTomy",
            "☑ codiREKT",
            "☑ codiREKTed",
            "☑ codiREKTing",
            "☑ codiREKTion",
            "☑ codiREKTions",
            "☑ codiREKTor",
            "☑ codiREKTors",
            "☑ codiREKTs",
            "☑ coeREKT",
            "☑ coeREKTed",
            "☑ coeREKTing",
            "☑ coeREKTs",
            "☑ coloREKTal",
            "☑ corREKT",
            "☑ corREKTable",
            "☑ corREKTed",
            "☑ corREKTer",
            "☑ corREKTest",
            "☑ corREKTing",
            "☑ corREKTion",
            "☑ corREKTional",
            "☑ corREKTions",
            "☑ corREKTitude",
            "☑ corREKTitudes",
            "☑ corREKTive",
            "☑ corREKTively",
            "☑ corREKTives",
            "☑ corREKTly",
            "☑ corREKTness",
            "☑ corREKTnesses",
            "☑ corREKTor",
            "☑ corREKTors",
            "☑ corREKTs",
            "☑ diREKT",
            "☑ diREKTed",
            "☑ diREKTedness",
            "☑ diREKTednesses",
            "☑ diREKTer",
            "☑ diREKTest",
            "☑ diREKTing",
            "☑ diREKTion",
            "☑ diREKTional",
            "☑ diREKTionalities",
            "☑ diREKTionality",
            "☑ diREKTionless",
            "☑ diREKTionlessness",
            "☑ diREKTionlessnesses",
            "☑ diREKTions",
            "☑ diREKTive",
            "☑ diREKTives",
            "☑ diREKTivities",
            "☑ diREKTivity",
            "☑ diREKTly",
            "☑ diREKTness",
            "☑ diREKTnesses",
            "☑ diREKTor",
            "☑ diREKTorate",
            "☑ diREKTorates",
            "☑ diREKTorial",
            "☑ diREKTories",
            "☑ diREKTors",
            "☑ diREKTorship",
            "☑ diREKTorships",
            "☑ diREKTory",
            "☑ diREKTress",
            "☑ diREKTresses",
            "☑ diREKTrice",
            "☑ diREKTrices",
            "☑ diREKTrix",
            "☑ diREKTrixes",
            "☑ diREKTs",
            "☑ endarteREKTomies",
            "☑ endarteREKTomy",
            "☑ eREKT",
            "☑ eREKTable",
            "☑ eREKTed",
            "☑ eREKTer",
            "☑ eREKTers",
            "☑ eREKTile",
            "☑ eREKTilities",
            "☑ eREKTility",
            "☑ eREKTing",
            "☑ eREKTion",
            "☑ eREKTions",
            "☑ eREKTive",
            "☑ eREKTly",
            "☑ eREKTness",
            "☑ eREKTnesses",
            "☑ eREKTor",
            "☑ eREKTors",
            "☑ eREKTs",
            "☑ gastREKTomies",
            "☑ gastREKTomy",
            "☑ hypercorREKT",
            "☑ hypercorREKTion",
            "☑ hypercorREKTions",
            "☑ hypercorREKTly",
            "☑ hypercorREKTness",
            "☑ hypercorREKTnesses",
            "☑ hysteREKTomies",
            "☑ hysteREKTomized",
            "☑ hysteREKTomy",
            "☑ incorREKT",
            "☑ incorREKTly",
            "☑ incorREKTness",
            "☑ incorREKTnesses",
            "☑ indiREKT",
            "☑ indiREKTion",
            "☑ indiREKTions",
            "☑ indiREKTly",
            "☑ indiREKTness",
            "☑ indiREKTnesses",
            "☑ insurREKTion",
            "☑ insurREKTional",
            "☑ insurREKTionaries",
            "☑ insurREKTionary",
            "☑ insurREKTionist",
            "☑ insurREKTionists",
            "☑ insurREKTions",
            "☑ misdiREKT",
            "☑ misdiREKTed",
            "☑ misdiREKTing",
            "☑ misdiREKTion",
            "☑ misdiREKTions",
            "☑ misdiREKTs",
            "☑ multidiREKTional",
            "☑ nephREKTomies",
            "☑ nephREKTomize",
            "☑ nephREKTomized",
            "☑ nephREKTomizes",
            "☑ nephREKTomizing",
            "☑ nephREKTomy",
            "☑ nondiREKTed",
            "☑ nondiREKTional",
            "☑ nondiREKTive",
            "☑ omnidiREKTional",
            "☑ oophoREKTomies",
            "☑ oophoREKTomy",
            "☑ oREKTic",
            "☑ oREKTive",
            "☑ overcorREKT",
            "☑ overcorREKTed",
            "☑ overcorREKTing",
            "☑ overcorREKTion",
            "☑ overcorREKTions",
            "☑ overcorREKTs",
            "☑ overdiREKT",
            "☑ overdiREKTed",
            "☑ overdiREKTing",
            "☑ overdiREKTs",
            "☑ porREKT",
            "☑ postresurREKTion",
            "☑ postresurREKTions",
            "☑ preeREKT",
            "☑ preeREKTed",
            "☑ preeREKTing",
            "☑ preeREKTs",
            "☑ REKTa",
            "☑ REKTal",
            "☑ REKTally",
            "☑ REKTangle",
            "☑ REKTangles",
            "☑ REKTangular",
            "☑ REKTangularities",
            "☑ REKTangularity",
            "☑ REKTangularly",
            "☑ REKTi",
            "☑ REKTifiabilities",
            "☑ REKTifiability",
            "☑ REKTifiable",
            "☑ REKTification",
            "☑ REKTifications",
            "☑ REKTified",
            "☑ REKTifier",
            "☑ REKTifiers",
            "☑ REKTifies",
            "☑ REKTify",
            "☑ REKTifying",
            "☑ REKTilinear",
            "☑ REKTilinearly",
            "☑ REKTitude",
            "☑ REKTitudes",
            "☑ REKTitudinous",
            "☑ REKTo",
            "☑ REKTor",
            "☑ REKTorate",
            "☑ REKTorates",
            "☑ REKTorial",
            "☑ REKTories",
            "☑ REKTors",
            "☑ REKTorship",
            "☑ REKTorships",
            "☑ REKTory",
            "☑ REKTos",
            "☑ REKTrices",
            "☑ REKTrix",
            "☑ REKTum",
            "☑ REKTums",
            "☑ REKTus",
            "☑ rediREKT",
            "☑ rediREKTed",
            "☑ rediREKTing",
            "☑ rediREKTion",
            "☑ rediREKTions",
            "☑ rediREKTs",
            "☑ reeREKT",
            "☑ reeREKTed",
            "☑ reeREKTing",
            "☑ reeREKTs",
            "☑ resurREKT",
            "☑ resurREKTed",
            "☑ resurREKTing",
            "☑ resurREKTion",
            "☑ resurREKTional",
            "☑ resurREKTionist",
            "☑ resurREKTionists",
            "☑ resurREKTions",
            "☑ resurREKTs",
            "☑ semieREKT",
            "☑ subdiREKTor",
            "☑ subdiREKTors",
            "☑ subeREKT",
            "☑ uncorREKTable",
            "☑ uncorREKTed",
            "☑ undiREKTed",
            "☑ unidiREKTional",
            "☑ unidiREKTionally",
            "☑ vitREKTomies",
            "☑ vitREKTomy"
    };

}
