main: net.thenamedev.legendarena.LegendArena
name: LegendArena
version: 1.0A
website: http://reddit.com/r/LegendArena
author: ThePixelDev
authors: [Legend Arena Devs, FOSS Contributors]
description: "§dLegend Arena plugin. §rThat's it. No, really, that's all there is to this plugin."
commands:
  firework:
    description: Fireworks! Yaaay!
    usage: /firework
  warp:
    description: Warps you to different areas. Whee!
    usage: /warp
  particles:
    description: Particles. Yay!
    usage: /particles
    aliases: [particle, ps]
  gadgets:
    description: Gadgets control command.
    usage: /gadgets [player]
  emeralds:
    description: Front-end command for the Emeralds system.
    usage: /emeralds <suboption> [args]
  staff:
    description: Various staff commands.
    usage: /staff <suboption> [args]
  help:
    description: It looks like you want help. Do you want help with that? #yeah that was bad I'll show myself out
    usage: /help
  dev:
    description: Developer utility command.
    usage: /dev [suboption] [args]
  chat:
    description: Change your chat channel.
    usage: /chat <channel> [msg]
    aliases: [c, sc]
  stafflist:
    description: Shows currently online staff, and their ranks.
    aliases: [sl, liststaff]
  troll:
    description: Trololololololololol, lololo!