main: legendarena.LegendArena
name: LegendArena
depend: [LegendAPI, KotlinLoader]
version: 1.0-SNAPSHOT
website: http://thenamedev.net/legendarena/
author: ThePixelDev
authors: [FOSS Contributors]
description: "§cLegend Arena custom plugin. §8Plugin source code: https://github.com/LegendArenaMC/LegendArena"
commands:
  firework:
    description: Fireworks! Yaaay!
    usage: /firework
    aliases: [fw]
  warp:
    description: Warps you to different areas. Whee!
    usage: /warp
  particles:
    description: Particles. Yay!
    usage: /particles
    aliases: [particle, ps]
  gadgets:
    description: Gadgets control command.
    usage: /gadgets [player]
  emeralds:
    description: Front-end command for the Emeralds system.
    usage: /emeralds <suboption> [args]
  staff:
    description: Various staff commands.
    usage: /staff <suboption> [args]
  help:
    description: It looks like you want help. Do you want help with that? #yeah that was bad I'll show myself out
    usage: /help
  dev:
    description: Developer utility command.
    usage: /dev [suboption] [args]
  chat:
    description: Change your chat channel.
    usage: /chat <channel> [msg]
    aliases: [c, sc, say]
  stafflist:
    description: Shows currently online staff, and their ranks.
    aliases: [sl, liststaff]
  troll:
    description: Trololololololololol, lololo!
  fly:
    description: Magic.